version: "3.7"

# IMPORTANT: starting this configuration via podman on linux doesn't start oracle services within container
#            this makes it impossible to connect to oracle database.
#            for working example with podman please see https://chumaky.team/blog/postgres-oracle-fdw
services:
  oracle:
    image: store/oracle/database-enterprise:12.2.0.1
    environment:
      # default "sys" user password mentioned in oracle image readme
      SYS_PASSWORD: Oradoc_db1
    ports:
      - 1521:1521

  postgres:
    # if you build image locally and tagged it as "postgres_oracle_fdw"
    image: postgres_oracle_fdw

    # if you want to use prebuilt image
    #image: toleg/postgres_oracle_fdw
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    #volumes:
    #  - "./sql/postgres_mysql_setup.sql:/docker-entrypoint-initdb.d/postgres_mysql_setup.sql:z"
    depends_on:
      - oracle


